### ISSUE TITLE
Implement Drop for MiniFs instead of unmount()

### ISSUE THREAD

**Issue by JMS55** [germangb/mini-fs#3]

**Comment by germangb** [comment]
[`umount`](https://germangb.github.io/mini-fs/mini_fs/struct.MiniFs.html#method.umount) is to the `MiniFs` what [`Vec::remove`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.remove) is to `Vec`. MiniFs isn't dropped by umount.

**Comment by JMS55** [comment]
Ah ok, based on the comment in the readme I thought otherwise, so you might want to clarify that: `// Unmount it when you're done (drops the file system)`
