### ISSUE TITLE
Rename structs

### ISSUE THREAD

**Issue by flaviojs** [germangb/mini-fs#4]
This is a suggestion.

As I stated in https://github.com/germangb/mini-fs/issues/1#issuecomment-488889733, the names were confusing me because it's not named with a filesystem perspective.

I suggest the following name changes:
 * Zip to ZipFs
 * Tar to TarFs
 * Local to LocalFs
 * Ram to RamFs
 * HelloWorld to HelloWorldFs
 * (if it always represents a file) ZipEntry to ZipFile or ZipFsFile
 * (if it always represents a file) TarEntry to TarFile or TarFsFile

I can make a PR after you give feedback.

**Comment by germangb** [comment]
Please, go ahead. Happy to merge :+1:
